INSERT INTO `adminpages` (`id`, `pageName`, `pageGroup`, `icon`, `route`, `displayOrder`, `created_at`, `updated_at`) VALUES
(1, 'Dashboard', NULL, 'columns', 'dashboard', 1, '2024-10-11 14:46:13', '2024-10-11 14:46:13'),
(2, 'Customers', NULL, 'users', 'customers', 2, NULL, NULL),
(3, 'Astrologers', NULL, 'target', NULL, 3, NULL, '2023-12-26 15:26:16'),
(4, 'Astroshop', NULL, 'shopping-bag', NULL, 4, NULL, NULL),
(5, 'Product Categories', 4, 'folder', 'productCategories', NULL, NULL, NULL),
(6, 'Products', 4, 'package-search', 'products', NULL, NULL, NULL),
(7, 'Orders', 4, 'indian-rupee', 'orders', NULL, NULL, NULL),
(8, 'Horoscope', NULL, 'star', NULL, 5, NULL, NULL),
(9, 'Daily HoroScope', 8, 'loader', 'dailyHoroscope', NULL, NULL, NULL),
(11, 'Weekly HoroScope', 8, 'loader', 'horoscope', NULL, NULL, NULL),
(12, 'Yearly HoroScope', 8, 'calendar', 'yearlyhoroscope', NULL, NULL, NULL),
(13, 'Blogs', NULL, 'pencil', 'blogs', 7, NULL, NULL),
(14, 'News', NULL, 'rss', 'astroguruNews', 7, NULL, NULL),
(15, 'Videos', NULL, 'youtube', 'adsVideos', 8, NULL, NULL),
(16, 'Tickets', 52, 'ticket', 'tickets', NULL, NULL, NULL),
(17, 'Earning', NULL, 'indian-rupee', NULL, 12, NULL, NULL),
(19, 'Withdrawal Requests', 17, 'check', 'withdrawalRequests', NULL, NULL, NULL),
(20, 'Reports', NULL, 'file', NULL, 13, NULL, NULL),
(21, 'Call History', 20, 'phone', 'callHistory', NULL, NULL, NULL),
(22, 'Chat History', 20, 'send', 'chatHistory', NULL, NULL, NULL),
(23, 'PartnerWise Earning', 20, 'indian-rupee', 'partnerWiseEarning', NULL, NULL, NULL),
(24, 'Order Request', 20, 'shopping-cart', 'orderrequest', NULL, NULL, NULL),
(25, 'Report Request', 20, 'files', 'reportrequest', NULL, NULL, NULL),
(27, 'Block Astrologer', 3, 'x', 'blockAstrologer', NULL, NULL, NULL),
(28, 'Master Settings', NULL, 'wrench', NULL, 14, NULL, NULL),
(31, 'Customer Avatars', 28, 'user', 'customerProfile', NULL, NULL, NULL),
(33, 'HoroScope Signs', 28, 'wand', 'horoscopeSigns', NULL, NULL, NULL),
(34, 'Report Type', 28, 'files', 'reportTypes', NULL, NULL, NULL),
(35, 'Banner Management', NULL, 'image', 'banners', 9, NULL, NULL),
(36, 'Notifications', NULL, 'bell-ring', 'notifications', 10, NULL, NULL),
(37, 'FAQs', 52, 'list', 'helpSupport', NULL, NULL, NULL),
(38, 'Recharge Amount', 28, 'indian-rupee', 'rechargeAmount', NULL, NULL, NULL),
(39, 'General Settings', NULL, 'settings', 'setting', 16, NULL, NULL),
(40, 'Feedback', NULL, 'smile', 'feedback', 17, NULL, NULL),
(41, 'Team Management', NULL, 'user', NULL, 15, NULL, NULL),
(42, 'Team Role', 41, 'equal', 'teamRole', NULL, NULL, NULL),
(43, 'Team List', 41, 'users', 'team-list', NULL, NULL, NULL),
(44, 'Manage astrologers', 3, 'folder', 'astrologers', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(45, 'Pending Requests', 3, 'circle', 'pending-requests', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(46, 'Reviews', 3, 'star', 'astrologerReview', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(47, 'Gifts', 3, 'gift', 'gifts', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(48, 'Skills', 3, 'pocket', 'skills', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(49, 'Categories', 3, 'folder', 'astrologerCategories', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(50, 'Commissionn rate for calls/ chats', 3, 'indian-rupee', 'commissions', NULL, '2023-12-26 15:26:16', '2023-12-26 15:26:16'),
(51, 'Horoscope Feedback', 8, 'smile', 'horoscopeFeedback', NULL, NULL, NULL),
(52, 'Support Management', NULL, 'bot', NULL, 11, NULL, NULL),
(53, 'Withdrawal Methods', 17, 'activity', 'withdrawalMethods', NULL, NULL, NULL),
(54, 'Kundali Report', 20, 'files', 'kundaliearning', NULL, NULL, NULL),
(55, 'Page Management', NULL, 'book-open', 'pages', 18, NULL, NULL),
(56, 'Recharge History', 17, 'history', 'walletHistory', NULL, NULL, NULL),
(60, 'Stories', NULL, 'play-circle', 'story-list', 9, NULL, NULL),
(61, 'Contact Form', NULL, 'contact', 'contactlist', 19, NULL, NULL),
(63, 'Puja', NULL, 'box', NULL, 6, NULL, NULL),
(64, 'Categories', 63, 'asterisk', 'puja-categories-list', NULL, NULL, NULL),
(65, 'Sub Categories', 63, 'asterisk', 'puja-subcategories-list', NULL, NULL, NULL),
(68, 'Puja Package', 63, 'package', 'package-list', NULL, NULL, NULL),
(69, 'Puja', 63, 'aperture', 'puja-list', NULL, NULL, NULL),
(70, 'Puja Faqs', 63, 'align-justify', 'puja-faq-list', NULL, NULL, NULL),
(71, 'Puja Orders', 63, 'shopping-cart', 'puja-order-list', NULL, NULL, NULL),
(72, 'Exotel Call History', 20, 'phone', 'exotel-report-list', NULL, NULL, NULL),
(73, 'Course', NULL, 'book', NULL, 6, NULL, NULL),
(74, 'Categories', 73, 'asterisk', 'course-categories-list', NULL, NULL, NULL),
(75, 'Course', 73, 'package', 'CourseList-list', NULL, NULL, NULL),
(76, 'Chapters', 73, 'align-justify', 'course-chapter-list', NULL, NULL, NULL),
(77, 'Course Orders', 73, 'shopping-cart', 'courseOrderList', NULL, NULL, NULL),
(78, 'Profile Boost Settings', 3, 'settings', 'profile-list', NULL, '2024-10-11 14:48:25', '2024-10-11 14:48:25'),
(79, 'Kundali Price', 28, 'indian-rupee', 'kundali-prices', NULL, NULL, NULL),
(80, 'Referral Settings', 28, 'settings', 'referral-settings', NULL, NULL, NULL),
(82, 'AI Astro Chat History', 20, 'bot', 'ai.astrologers.chat.history', NULL, NULL, '2023-12-26 20:56:16'),
(83, 'AI Counsellor', NULL, 'bot', NULL, 3, NULL, '2023-12-26 20:56:16'),
(84, 'AI Chat Bot', 83, 'bot', 'ai.chat.bot', NULL, NULL, '2023-12-26 20:56:16'),
(87, 'Data Monitoring', NULL, 'monitor', NULL, 22, NULL, NULL),
(88, 'Chats Monitoring', 87, 'message-circle', 'chats.monitoring', NULL, NULL, NULL),
(89, 'Calls Monitoring', 87, 'phone', 'calls.monitoring', NULL, NULL, NULL),
(90, 'Block Keywords', 87, 'x', 'block.keywords', NULL, NULL, NULL),
(91, 'Profile Boost History', 3, 'rocket', 'profileBoostHistory', NULL, '2024-10-11 14:48:25', '2024-10-11 14:48:25'),
(92, 'Product Recommend', 4, 'shopping-cart', 'productRecommend', NULL, NULL, NULL),
(93, 'Astrologer Assistant', 3, 'bot', 'astrologerAssistant', NULL, NULL, NULL),
(94, 'Admin Earnings', 17, 'indian-rupee', 'adminEarnings', NULL, NULL, NULL),
(95, 'Astrologer Earnings', 17, 'indian-rupee', 'astrologerEarning', NULL, NULL, NULL),
(96, 'Document List', 3, 'file', 'document', NULL, '2023-12-26 20:56:16', '2023-12-26 20:56:16'),
(97, 'Website Faq', 28, 'list', 'web-faq-list', NULL, NULL, NULL),
(98, 'Email Template', NULL, 'mail', 'getEmailTemplate', 23, NULL, NULL),
(99, 'Puja Recommend', 63, 'list', 'pujaRecommend', NULL, NULL, NULL),
(100, 'App Design', NULL, 'palette', 'getAppdesign', 24, NULL, NULL),
(101, 'Astrologer Puja', 63, 'aperture', 'astrologer-puja-list', NULL, NULL, NULL),
(102, 'Training Video', 28, 'youtube', 'getTrainingVideo', NULL, NULL, NULL);
